id: P5939B33C
initial_creation_type: input
source_metadata:
  title: Amitābha and Sukhāvatī Series
  language: bo
  description: 'Texts and practices related to Buddha Amitābha and his pure-land,
    the blissful western paradise of Sukhāvatī (bde ba can), including prayers of
    aspiration to be reborn in Sukhāvatī (bde smon):'
  volume:
    1db298dbbd7840f8a3a558aa737e4eaf:
      title: Aspiration for Rebirth in Sukhāvatī
      parent: Aspiration Prayers (bde smon)
    edc30c8e63e34d408b3f5d4c3508cb7a:
      title: Prayer to Buddha Amitābha
      parent: Aspiration Prayers (bde smon)
    131b2620a3064fbb81394d5a6cd3cf17:
      title: A Sukhāvatī Prayer and Aspiration
      parent: Aspiration Prayers (bde smon)
    138314d162f24cb5807e7c47b735701e:
      title: Brief Sukhāvatī Aspiration
      parent: Aspiration Prayers (bde smon)
    ffddcea0c427442aa8b6a4279146b4d0:
      title: Aspiration for the Land of Great Bliss
      parent: Aspiration Prayers (bde smon)
    a26570bcb62145fd88fb1c3c073aad2c:
      title: Aspiration to Be Reborn in the Realm of Sukhāvatī
      parent: Aspiration Prayers (bde smon)
    4a017e7421e74a82b5db3919e0269bc5:
      title: Prayer of Aspiration Towards Sukhāvatī
      parent: Aspiration Prayers (bde smon)
    44eb7086f8f4470ca51b5aea3ee32dad:
      title: Sukhāvatī Aspiration
      parent: Aspiration Prayers (bde smon)
    2e4460ef519e470d93a1b548cebee5bd:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Aspiration Prayers (bde smon)
    14356b448e944af3a548a1d7e94e929c:
      title: Prayer to Behold Amitābha in Dreams
      parent: Aspiration Prayers (bde smon)
    9582e1a0a7f9463c81f9713f6d03e5e6:
      title: Verso Inscription on an Image of the Pure Land of Great Bliss
      parent: Inscriptions
    c1e5f73cfd4f4a13be47db24b4c6f51f:
      title: Brief Amitābha Sleeping Practice
      parent: Meditation
    a296aeebcb3241f993ab3c1e9d530917:
      title: Meditation on Amitābha
      parent: Meditation
    1f97cdc4a519452d90f5daabcbca107e:
      title: 'The Swift Path to Great Bliss: A Sādhana of Amitābha, Buddha of Limitless
        Light'
      parent: Sādhanas
created_at: '2022-03-01T02:41:42.989335'
last_modified_at: '2022-03-01T02:41:42.989338'
